/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPopover: typeof import('./src/components/AccountPopover.vue')['default']
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppNotification: typeof import('./src/components/AppNotification.vue')['default']
    LayoutAside: typeof import('./src/components/LayoutAside.vue')['default']
    LayoutMobileAside: typeof import('./src/components/LayoutMobileAside.vue')['default']
    LayoutToggleSidebar: typeof import('./src/components/LayoutToggleSidebar.vue')['default']
    LayoutTopBar: typeof import('./src/components/LayoutTopBar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NTag: typeof import('naive-ui')['NTag']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebLogo: typeof import('./src/components/WebLogo.vue')['default']
    WebUpdateLog: typeof import('./src/components/WebUpdateLog.vue')['default']
    WebWelcomePage: typeof import('./src/components/WebWelcomePage.vue')['default']
  }
}
